<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="MainForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Menus\AjouterMenuForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Menus\AfficherMenuForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Menus\ModifierMenuForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Clients\AjouterClientForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Clients\AfficherClientForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Clients\ModifierClientForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Paiements\AfficherPaiementForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Paiements\AjouterPaiementForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Paiements\ModifierPaiementForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Users\Login.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Users\AfficherUserForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Users\AjouterUserForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Users\ModifierUserForm.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Views\Parametres\ParametreForm.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>
	
	<ItemGroup>
      <Reference Include="MySql.Data">
        <HintPath>..\..\..\..\..\Program Files (x86)\MySQL\MySQL Installer for Windows\MySql.Data.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MySqlConnector" Version="2.5.0" />
    </ItemGroup>

</Project>